# Change these first
owner: fij0 # Your GitHub organization or username, where this repository lives
repo: up-moodlefce # The name of this repository

sites:
  - name: Grado
    url: https://moodle.fce.uncu.edu.ar
  - name: Posgrado
    url: https://eposgrado.fce.uncu.edu.ar
  - name: Extension
    url: https://eextension.fce.uncu.edu.ar
  - name: Ingreso
    url: https://eingreso.fce.uncu.edu.ar
  - name: Adistancia
    url: https://adistancia.fce.uncu.edu.ar
